import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../styles/globals.css'

import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
    children: ReactNode
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="w-full h-screen bg-gray-900 flex items-center justify-center flex-col">
                    <main className="w-full h-[calc(100vh-4rem)] p-4 flex items-center justify-center flex-col">
                        {children}

                        <audio id="s_keyq" src="/sounds/keyq.wav"></audio>
                        <audio id="s_keyw" src="/sounds/keyw.wav"></audio>
                        <audio id="s_keye" src="/sounds/keye.wav"></audio>
                        <audio id="s_keya" src="/sounds/keya.wav"></audio>
                        <audio id="s_keys" src="/sounds/keys.wav"></audio>
                        <audio id="s_keyd" src="/sounds/keyd.wav"></audio>
                        <audio id="s_keyz" src="/sounds/keyz.wav"></audio>
                        <audio id="s_keyx" src="/sounds/keyx.wav"></audio>
                        <audio id="s_keyc" src="/sounds/keyc.wav"></audio>
                    </main>

                    <Footer />
                </div>
            </body>
        </html>
    )
}
